export type SourceKind = "api" | "export" | "portal" | "foundation" | "network";
export type SourceAccess = "connected" | "open" | "requires_account" | "to_verify";

export type ExternalSource = {
  id: string;
  name: string;
  kind: SourceKind;
  access: SourceAccess;
  officialUrl: string;
  dataUrl?: string;
  coverage: string;
  supports: string[];
  checkedAt: string;
  notes: string;
};

export const sourceRegistry: ExternalSource[] = [
  { id: "aides-entreprises-api", name: "Aides-Entreprises", kind: "api", access: "connected", officialUrl: "https://data.aides-entreprises.fr/api", dataUrl: "https://data.aides-entreprises.fr/api", coverage: "France · aides aux entreprises", supports: ["API REST", "CSV", "JSON", "XML", "webhook"], checkedAt: "2026-09-02", notes: "Headers serveur X-Aidesentreprises-Id et X-Aidesentreprises-Key configurés ; route de consultation à valider dans la documentation fournisseur." },
  { id: "aides-entreprises-open-data", name: "Aides-Entreprises — export open data", kind: "export", access: "open", officialUrl: "https://www.data.gouv.fr/datasets/base-de-donnees-des-aides-aux-entreprises", dataUrl: "https://data.cquest.org/dge_aides_entreprises/aides.json", coverage: "France · aides publiques aux entreprises", supports: ["JSON", "CSV", "XML"], checkedAt: "2026-09-02", notes: "Licence Ouverte signalée sur data.gouv.fr ; export volumineux à importer en tâche contrôlée, pas à charger dans le navigateur." },
  { id: "aides-territoires", name: "Aides Territoires", kind: "api", access: "requires_account", officialUrl: "https://aides-territoires.beta.gouv.fr/api", dataUrl: "https://aides-territoires.beta.gouv.fr/api/aids/", coverage: "Territoires · aides financières et ingénierie", supports: ["API REST", "filtres par périmètre", "critères"], checkedAt: "2026-09-02", notes: "API documentée ; les routes répondent avec Bearer token. Ne pas appeler sans jeton autorisé." },
  { id: "associations-gouv-appels", name: "Associations.gouv.fr — appels à projets", kind: "portal", access: "open", officialUrl: "https://associations.gouv.fr/appels-projets", coverage: "France · associations · FDVA, appels à projets et AMI", supports: ["veille éditoriale", "FDVA", "AMI", "Le Compte Asso"], checkedAt: "2026-09-02", notes: "Licence Etalab 2.0 signalée ; renvoi obligatoire vers la page et le règlement du financeur." },
  { id: "service-public", name: "Service-Public.fr", kind: "portal", access: "open", officialUrl: "https://www.service-public.gouv.fr", coverage: "France · particuliers, entreprises et démarches", supports: ["fiches officielles", "simulateurs", "démarches"], checkedAt: "2026-09-02", notes: "Source d’orientation ; pas de scraping massif. Les fiches sont à relier individuellement avec leur date de vérification." },
  { id: "anah-france-renov", name: "Anah / France Rénov’", kind: "portal", access: "open", officialUrl: "https://www.anah.gouv.fr", dataUrl: "https://france-renov.gouv.fr/aides/maprimerenov", coverage: "France · rénovation, adaptation, habitat privé", supports: ["guides datés", "aides travaux", "orientation"], checkedAt: "2026-09-02", notes: "Aucune API publique évidente identifiée ; utiliser les guides et pages officielles avec vérification manuelle." },
  { id: "justice-aide-juridictionnelle", name: "Justice.fr — aide juridictionnelle", kind: "portal", access: "open", officialUrl: "https://www.justice.fr/simulateurs/aide-juridictionnelle", dataUrl: "https://www.aidejuridictionnelle.justice.fr/simulateur", coverage: "France · particuliers · frais de justice", supports: ["simulateur", "démarche en ligne", "barème"], checkedAt: "2026-09-02", notes: "À classer comme aide aux particuliers et orientation juridique, hors financement courant des entreprises." },
  { id: "ecologie-aides-mobilite", name: "Écologie — aides à la mobilité électrique", kind: "portal", access: "open", officialUrl: "https://www.ecologie.gouv.fr/presse/plan-delectrification-aides-lacquisition-vehicules-electriques-taxis-disponibles-1er", coverage: "France · véhicules électriques · taxis/VTC et mobilité", supports: ["aides véhicules", "plan sectoriel", "mobilité"], checkedAt: "2026-09-02", notes: "Page officielle d’information ; vérifier le dispositif actif et les critères sur le guichet indiqué avant recommandation." },
  { id: "data-subvention", name: "Data.Subvention", kind: "api", access: "requires_account", officialUrl: "https://datasubvention.beta.gouv.fr/api/", dataUrl: "https://api.datasubvention.beta.gouv.fr/docs/", coverage: "Associations · données administratives et demandes de subvention", supports: ["API", "Swagger", "open data partiel"], checkedAt: "2026-09-02", notes: "Usage principalement administratif ; contacter l’équipe avant d’exposer des données associatives dans un annuaire public." },
  { id: "fondation-de-france", name: "Fondation de France", kind: "foundation", access: "open", officialUrl: "https://www.fondationdefrance.org/fr/appels-a-projets", coverage: "France · appels à projets, AMI, recherche, solidarité, environnement", supports: ["annuaire d’appels", "statut en cours/à venir/clos"], checkedAt: "2026-09-02", notes: "Pas d’API publique identifiée pendant l’audit ; veille par page officielle et validation manuelle recommandée." },
  { id: "admical", name: "Admical", kind: "foundation", access: "open", officialUrl: "https://admical.org/categories-articles/les-appels-projets", coverage: "France · mécénat d’entreprise et appels à projets", supports: ["veille éditoriale", "mécénat", "formation"], checkedAt: "2026-09-02", notes: "Source de veille et d’orientation, pas un financeur unique." },
  { id: "appel-a-projets-org", name: "Appel à projets", kind: "foundation", access: "open", officialUrl: "https://www.appelaprojets.org/", coverage: "France · appels à projets, AMI, concours, mécénat", supports: ["moteur de recherche", "veille"], checkedAt: "2026-09-02", notes: "À utiliser comme source secondaire ; toujours renvoyer vers le règlement et le site du financeur." },
  { id: "concours-talents", name: "Concours Talents", kind: "network", access: "open", officialUrl: "https://www.concours-talents.com/", coverage: "France · concours de création et reprise d’entreprise", supports: ["concours", "candidature", "réseau d’accompagnement"], checkedAt: "2026-09-02", notes: "Source officielle du concours ; les dates, catégories et dotations doivent être vérifiées à chaque campagne." },
  { id: "drac-occitanie-mecenat", name: "DRAC Occitanie — mécénat", kind: "foundation", access: "open", officialUrl: "https://www.culture.gouv.fr/regions/drac-occitanie/demandes-de-subventions-a-la-drac-occitanie/le-mecenat-a-la-drac-occitanie", coverage: "Occitanie · projets culturels et intérêt général", supports: ["accompagnement mécénat", "orientation"], checkedAt: "2026-09-02", notes: "Partenaire d’orientation pour structurer une recherche de mécènes." },
  { id: "occitanie-angels", name: "Occitanie Angels", kind: "network", access: "open", officialUrl: "https://occitanie-angels.fr/", coverage: "Occitanie · business angels et entreprises innovantes", supports: ["investissement", "mise en relation", "accompagnement"], checkedAt: "2026-09-02", notes: "Réseau d’investisseurs ; l’éligibilité et la sélection dépendent du réseau et du dossier." },
];
